version: '3.7'

services:

  # Backend
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "4201:8080"
    env_file:
      - .env
    volumes:
      - ./app:/app
    networks:
      - pinetwork
    depends_on: 
      - database
    command:
      sh -c  "uvicorn main:app --host 0.0.0.0 --debug --port 8080 --reload-dir /app"

     # Database
  database:
    image: mysql:5.7
    # volumes:
    #   - ./db_data:/var/lib/mysql
    #   - ./db_init:/docker-entrypoint-initdb.d/:ro
    user: mysql
    restart: always
    ports:
      - '32000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: pi
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1q2w3e4r
    networks:
      - pinetwork

networks:
  pinetwork:
